export interface gameValues {
  centreLetter: string;
  wordList: string[];
  letters: string[];
  totalPoints: number;
}

export const defaultValues: gameValues = {
  centreLetter: "f",
  wordList: [
    "ingulfing",
    "flinging",
    "unfixing",
    "flung",
    "flux",
    "gulf",
    "flinging",
    "fluffing",
    "fluxing",
    "fugling",
    "fuguing",
    "fulling",
    "gulfing",
    "luffing",
    "lungful",
    "niffing",
    "fluff",
    "filling",
    "fifing",
    "filing",
    "fining",
    "fixing",
    "fulfil",
    "infill",
    "influx",
    "ingulf",
    "fling",
    "flung",
    "fungi",
    "gliff",
    "infix",
    "unfix",
    "fill",
    "flux",
    "fugu",
    "full",
    "guff",
    "gulf",
    "luff",
    "niff",
    "nuff",
  ],
  letters: ["g", "l", "u", "x", "i", "n"],
  totalPoints: 182,
};
